version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/rails/Dockerfile
      args:
        RUBY_VERSION: '2.7.1'
        RAILS_VERSION: '6.0.2.2'
        PG_MAJOR: '11'
        NODE_MAJOR: '12'
        YARN_VERSION: '1.13.0'
        BUNDLER_VERSION: '2.0.2'
        WORKDIR: '/app'
    image: sherllo/rails:6.0.2.2
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    command: /bin/bash
    ports:
      - '3000:3000'
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/app/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - ../rails-template:/rails-template
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      # comment out when not using postgres
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - PSQL_HISTFILE=/app/log/.psql_history
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - EDITOR=vim
    depends_on:
      # comment out when not using MySQL
     #- mysql
      # comment out when not using postgres
      - postgres
      - redis

  postgres:
    image: postgres:11.1
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - 5432

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
  rails-template: